set nocompatible  " be iMproved, required

set exrc
set encoding=UTF-8

syntax enable
set background=dark
set ruler
set hidden
set number
set ruler
set showcmd
set incsearch " Highlight the search results

set number relativenumber
set nu rnu


" color skittles_berry

call plug#begin()
	
	Plug 'scrooloose/nerdtree'
	Plug 'vim-scripts/L9' " helpers
	
    " ==== Get code snippets when needed
    Plug 'dbeniamine/cheat.sh-vim'
    " Plug 'mickaobrien/vim-stackoverflow'
	
    " ==== Completion
	" Plug 'Valloric/YouCompleteMe'
    Plug 'scrooloose/nerdcommenter'

	" ==== Git
	Plug 'airblade/vim-gitgutter'
	Plug 'tpope/vim-fugitive'

	" ==== syntax helpers
	Plug 'scrooloose/syntastic'
	Plug 'tpope/vim-surround'
	Plug 'cakebaker/scss-syntax.vim'
	Plug 'othree/yajs.vim'
	Plug 'mitsuhiko/vim-jinja'
	Plug 'octol/vim-cpp-enhanced-highlight'
	Plug 'ap/vim-css-color'
	Plug 'Vimjas/vim-python-pep8-indent'
	Plug 'python-rope/rope'
	Plug 'python-rope/ropemode'
	Plug 'python-rope/ropevim'
	Plug 'klen/pylama'

	" ==== moving / searching
	Plug 'easymotion/vim-easymotion'
	Plug 'kien/ctrlp.vim'
	Plug 'ervandew/supertab'
	Plug 'terryma/vim-multiple-cursors'

	" ==== snippets
	" Plug 'SirVer/ultisnips'

	" Status bar on bottom
	Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'powerline/fonts'

	" ==== PLUGIN THEMES
	Plug 'morhetz/gruvbox'
call plug#end()

filetype plugin indent on

let g:airline_powerline_fonts = 1 " Required for correct use of airline

" ==== Colors and other basic settings
colorscheme gruvbox
"set guifont=Monospace\ 10

set fillchars+=vert:\$
set laststatus=2
set smartindent
set st=4 sw=4 et
set shiftwidth=4
set tabstop=4

let &colorcolumn="80"
:set guioptions-=m  "remove menu bar
:set guioptions-=T  "remove toolbar
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar


" ==== NERDTREE
let NERDTreeIgnore = ['__pycache__', '\.pyc$', '\.o$', '\.so$', '\.a$', '\.swp', '*\.swp', '\.swo', '\.swn', '\.swh', '\.swm', '\.swl', '\.swk', '\.sw*$', '[a-zA-Z]*egg[a-zA-Z]*', '.DS_Store']

let NERDTreeShowHidden=1
let g:NERDTreeWinPos="left"
let g:NERDTreeDirArrows=0
map <C-t> :NERDTreeToggle<CR>

" ==== Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_mri_args = "--config=$HOME/.jshintrc"
let g:syntastic_python_checkers = [ 'pylint', 'flake8', 'pep8', 'python']
let g:syntastic_yaml_checkers = ['jsyaml']
let g:syntastic_html_tidy_exec = 'tidy5'

" === flake8
let g:flake8_show_in_file=1

" ==== Easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
nmap f <Plug>(easymotion-s)

" ==== moving around
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

" ==== disable mouse
set mouse=c

" ==== disable swap file warning
set shortmess+=A

" ==== custom commands
command JsonPretty execute ":%!python -m json.tool"
set secure
