#!/usr/bin/env bash

####################################################
# CREATION     : 2016-06-01
# MODIFICATION : 2016-06-01

# I3block's blocklet which using xkblayout-state:
# - Display current keyboard layout
# - Set next/previous layout with the mouse
####################################################

cd ~/.config/i3/i3blocks-modules/

case $BLOCK_BUTTON in
    4) ./xkblayout-state set -1;;  # wheel up
    5) ./xkblayout-state set +1;;  # wheel down
esac

layout=$(./xkblayout-state print %s)

if [ "${layout}" = "us" ]; then
	echo "<span color=\"#FF0000\">EN</span>"
elif [ "${layout}" = "gr" ]; then
	echo "<span color=\"#FF0000\">GR</span>"
fi
#echo "$layout"
#echo "\\#FF0000"

